<?php

namespace modules\feedback\models;

use common\models\MActiveRecord;

/**
 * This is the model class for table "feedback_support".
 *
 * @property int $id
 * @property string $url
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $contact
 * @property string $file
 * @property string $created_at
 * @property string $updated_at
 * @property string $message
 * @property string $answer
 * @property int $status
 */
class Support extends MActiveRecord
{
    const STATUS_NEW = 0;
    const STATUS_WAIT = 1;
    const STATUS_READ = 2;
    const STATUS_ANSWER = 3;
    const STATUS_COMPLETE = 4;
    const STATUS_DELETE = 5;

    const STATUS_LIST = [
        self::STATUS_NEW      => 'Новый',
        self::STATUS_WAIT     => 'Ожидает',
        self::STATUS_READ     => 'Прочитан',
        self::STATUS_ANSWER   => 'Отвечен',
        self::STATUS_COMPLETE => 'Завершен',
    ];

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'feedback_support';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['answer'], 'string'],
            [['file'], 'file'],
            [['created_at', 'updated_at'], 'safe'],
            [['status'], 'integer'],
            [['name', 'email', 'phone', 'contact', 'url'], 'string', 'max' => 255],
            [['message'], 'string', 'max' => 1000],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id'         => 'ID',
            'url'        => 'Страница, с которой отправлена заявка',
            'name'       => 'Имя',
            'email'      => 'Email',
            'phone'      => 'Телефон',
            'contact'    => 'Контакты',
            'message'    => 'Сообщение',
            'answer'     => 'Ответ',
            'status'     => 'Статус',
            'created_at' => 'Создан',
            'updated_at' => 'Изменен',
        ];
    }

    /**
     * {@inheritdoc}
     * @return SupportQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SupportQuery(get_called_class());
    }
}
